### ISSUE TITLE
Error sending command.

### ISSUE THREAD

**Issue by BhaturaGuy** [CogentRedTester/mpv-changerefresh#7]
![image](https://user-images.githubusercontent.com/93109835/215323516-d57b4ddb-3bc4-41d1-bb37-50134c584098.png)
Logs: 
[mpv.log](https://github.com/CogentRedTester/mpv-changerefresh/files/10529656/mpv.log)

**Comment by CogentRedTester** [comment]
I have added a new debug statement in the last commit, please try again and send me a new log. Just to confirm: the script is failing to change your display right? Or is it succeeding but the script is printing this error message anyway?

**Comment by WhoMI7** [comment]
[mpv.log](https://github.com/CogentRedTester/mpv-changerefresh/files/10529874/mpv.log)

> is it succeeding but the script is printing this error message anyway

I don't think it is, since I could feel through the mouse movement that refresh rate was 144hz. After I closed mpv I got a  black screen (for 2 secs) and it became 60hz and unresponsive for around 20 secs (I have Mid end PC).

**Comment by WhoMI7** [comment]
Okay, there wasn't a problem, all I needed to do was add custom resolution with custom refresh rate to NVCP.
